"""add photographer website module

Revision ID: 084deefac87a
Revises: 9be6a2496c83
Create Date: 2026-09-15 17:13:10.363418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084deefac87a'
down_revision: Union[str, Sequence[str], None] = '9be6a2496c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photography_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_rm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_label', sa.String(length=100), nullable=True),
    sa.Column('features_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photography_packages_workspace_id'), 'photography_packages', ['workspace_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_workspace_id'), 'portfolio_items', ['workspace_id'], unique=False)
    op.create_table('website_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('favicon_url', sa.String(length=1000), nullable=True),
    sa.Column('hero_title', sa.String(length=255), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sa.String(length=1000), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=100), nullable=True),
    sa.Column('about_title', sa.String(length=255), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('about_image_url', sa.String(length=1000), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=1000), nullable=True),
    sa.Column('facebook_url', sa.String(length=1000), nullable=True),
    sa.Column('tiktok_url', sa.String(length=1000), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_settings_workspace_id'), 'website_settings', ['workspace_id'], unique=True)
    op.drop_constraint(op.f('fk_profiles_auth_user'), 'profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_profiles_auth_user'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_website_settings_workspace_id'), table_name='website_settings')
    op.drop_table('website_settings')
    op.drop_index(op.f('ix_portfolio_items_workspace_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_photography_packages_workspace_id'), table_name='photography_packages')
    op.drop_table('photography_packages')
    # ### end Alembic commands ###
