"""add client gallery trash

Revision ID: 2bf2a2e15e2a
Revises: 258f968fadd1
Create Date: 2026-09-17 17:06:55.404822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf2a2e15e2a'
down_revision: Union[str, Sequence[str], None] = '258f968fadd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_galleries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_client_galleries_deleted_at'), 'client_galleries', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_galleries_deleted_at'), table_name='client_galleries')
    op.drop_column('client_galleries', 'deleted_at')
    # ### end Alembic commands ###
