"""link website media assets

Revision ID: e6f5b466e099
Revises: 248cd16cd042
Create Date: 2026-09-15 19:45:00.051908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f5b466e099'
down_revision: Union[str, Sequence[str], None] = '248cd16cd042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_items', sa.Column('media_asset_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_portfolio_items_media_asset_id'), 'portfolio_items', ['media_asset_id'], unique=False)
    op.create_foreign_key(None, 'portfolio_items', 'media_assets', ['media_asset_id'], ['id'], ondelete='SET NULL')
    op.add_column('website_settings', sa.Column('logo_media_asset_id', sa.UUID(), nullable=True))
    op.add_column('website_settings', sa.Column('hero_media_asset_id', sa.UUID(), nullable=True))
    op.add_column('website_settings', sa.Column('about_media_asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'website_settings', 'media_assets', ['hero_media_asset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'website_settings', 'media_assets', ['logo_media_asset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'website_settings', 'media_assets', ['about_media_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'website_settings', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'website_settings', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'website_settings', type_='foreignkey')
    op.drop_column('website_settings', 'about_media_asset_id')
    op.drop_column('website_settings', 'hero_media_asset_id')
    op.drop_column('website_settings', 'logo_media_asset_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'portfolio_items', type_='foreignkey')
    op.drop_index(op.f('ix_portfolio_items_media_asset_id'), table_name='portfolio_items')
    op.drop_column('portfolio_items', 'media_asset_id')
    # ### end Alembic commands ###
