"""add client gallery foundation

Revision ID: f9cdb0f95531
Revises: e6f5b466e099
Create Date: 2026-09-17 03:44:39.958105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cdb0f95531'
down_revision: Union[str, Sequence[str], None] = 'e6f5b466e099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_galleries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shoot_date', sa.Date(), nullable=True),
    sa.Column('privacy_mode', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('access_token_hash', sa.String(length=255), nullable=True),
    sa.Column('allow_downloads', sa.Boolean(), nullable=False),
    sa.Column('allow_favourites', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("privacy_mode IN ('PUBLIC', 'PRIVATE', 'PASSWORD')", name='ck_client_galleries_privacy_mode'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_client_galleries_workspace_slug')
    )
    op.create_index(op.f('ix_client_galleries_expires_at'), 'client_galleries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_client_galleries_is_published'), 'client_galleries', ['is_published'], unique=False)
    op.create_index(op.f('ix_client_galleries_privacy_mode'), 'client_galleries', ['privacy_mode'], unique=False)
    op.create_index(op.f('ix_client_galleries_slug'), 'client_galleries', ['slug'], unique=False)
    op.create_index(op.f('ix_client_galleries_workspace_id'), 'client_galleries', ['workspace_id'], unique=False)
    op.create_table('gallery_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('gallery_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.String(length=1500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['client_galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_photos_gallery_id'), 'gallery_photos', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_gallery_photos_object_key'), 'gallery_photos', ['object_key'], unique=True)
    op.create_index(op.f('ix_gallery_photos_status'), 'gallery_photos', ['status'], unique=False)
    op.create_index(op.f('ix_gallery_photos_workspace_id'), 'gallery_photos', ['workspace_id'], unique=False)
    op.create_table('gallery_favourites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('gallery_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('visitor_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['client_galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['gallery_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'visitor_token', name='uq_gallery_favourites_photo_visitor')
    )
    op.create_index(op.f('ix_gallery_favourites_gallery_id'), 'gallery_favourites', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_gallery_favourites_photo_id'), 'gallery_favourites', ['photo_id'], unique=False)
    op.create_index(op.f('ix_gallery_favourites_visitor_token'), 'gallery_favourites', ['visitor_token'], unique=False)
    op.create_index(op.f('ix_gallery_favourites_workspace_id'), 'gallery_favourites', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_favourites_workspace_id'), table_name='gallery_favourites')
    op.drop_index(op.f('ix_gallery_favourites_visitor_token'), table_name='gallery_favourites')
    op.drop_index(op.f('ix_gallery_favourites_photo_id'), table_name='gallery_favourites')
    op.drop_index(op.f('ix_gallery_favourites_gallery_id'), table_name='gallery_favourites')
    op.drop_table('gallery_favourites')
    op.drop_index(op.f('ix_gallery_photos_workspace_id'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_status'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_object_key'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_gallery_id'), table_name='gallery_photos')
    op.drop_table('gallery_photos')
    op.drop_index(op.f('ix_client_galleries_workspace_id'), table_name='client_galleries')
    op.drop_index(op.f('ix_client_galleries_slug'), table_name='client_galleries')
    op.drop_index(op.f('ix_client_galleries_privacy_mode'), table_name='client_galleries')
    op.drop_index(op.f('ix_client_galleries_is_published'), table_name='client_galleries')
    op.drop_index(op.f('ix_client_galleries_expires_at'), table_name='client_galleries')
    op.drop_table('client_galleries')
    # ### end Alembic commands ###
